export const maxDuration = 300;

import {
  allowMethods, appError, cleanText, createDownloadTicket, db, enforceJsonBodySize,
  ensureConversationOwner, errorDetails, fetchWithTimeout, finalizeAiTokens, getOpenRouterVideoModels,
  getToolModelSettings, handleError, isLowBalance, json, localize, normalizeRequestId,
  releaseAiTokens, requestLocale, requireUser, reserveAiTokens, reservationTokens, requestIp, enforceRateLimit,
  TOKEN_USD, verifyDownloadTicket, videoPricePerSecond, videoPriceForRequest
} from './_lib.js';

const VIDEO_BUCKET='generated-images';
const MAX_VIDEO_BYTES=80*1024*1024;
const enumValues=(descriptor,fallback=[])=>Array.isArray(descriptor)?descriptor.map(String):(Array.isArray(descriptor?.values)?descriptor.values.map(String):fallback);
const chooseEnum=(descriptor,requested,preferred=[])=>{
  const values=enumValues(descriptor,[]);if(!values.length)return null;
  const exact=values.find(v=>String(v).toLowerCase()===String(requested||'').toLowerCase());if(exact)return exact;
  for(const wanted of preferred){const match=values.find(v=>String(v).toLowerCase()===String(wanted).toLowerCase());if(match)return match;}
  return values[0];
};
function videoEstimate(model,duration,resolution,aspectRatio){const seconds=Math.max(1,Number(duration)||5),rate=videoPriceForRequest(model,{resolution,aspectRatio})||videoPricePerSecond(model,{resolution,aspectRatio})||0.05,providerUsd=rate*seconds*1.05;return {seconds,rate,providerUsd,chargedTokens:Math.max(1,Math.ceil(providerUsd/TOKEN_USD))};}
function validOpenRouterPollUrl(value){try{const u=new URL(String(value||''),'https://openrouter.ai');return u.protocol==='https:'&&u.hostname==='openrouter.ai'&&u.pathname.startsWith('/api/v1/videos/')?u.toString():''}catch{return ''}}
function detectVideoType(file,declared=''){if(!Buffer.isBuffer(file)||file.length<12)return '';const d=String(declared||'').toLowerCase();if(file.toString('ascii',4,8)==='ftyp')return 'video/mp4';if(file.subarray(0,4).equals(Buffer.from([0x1a,0x45,0xdf,0xa3])))return d.includes('webm')?'video/webm':'video/webm';return ''}
function extensionFor(type){return type==='video/webm'?'webm':'mp4'}
function safeFilename(id,type){return `AiWay-${String(id||'video').replace(/[^a-zA-Z0-9_-]/g,'-').slice(0,80)}.${extensionFor(type)}`}
async function getOwnedVideo(userId,id){const {data,error}=await db().from('generated_images').select('*').eq('id',id).eq('user_id',userId).single();if(error||!data||!String(data.media_type||'').startsWith('video/'))throw appError('FILE_NOT_FOUND');return data}
async function makeViewUrl(userId,id){const ticket=await createDownloadTicket({sub:userId,imageId:id,kind:'video-view'},'2h');return `/api/video?action=view&ticket=${encodeURIComponent(ticket)}`}

async function serveVideo(req,res,inline){const ticket=await verifyDownloadTicket(req.query?.ticket);const expected=inline?'video-view':'video-download';if(ticket.kind!==expected||!ticket.imageId||!ticket.sub)throw appError('UNAUTHORIZED');const row=await getOwnedVideo(String(ticket.sub),String(ticket.imageId));if(!row.storage_path)throw appError('FILE_NOT_FOUND');const type=String(row.media_type||'video/mp4');const filename=safeFilename(row.id,type);const {data,error}=await db().storage.from(VIDEO_BUCKET).createSignedUrl(row.storage_path,300,inline?{}:{download:filename});if(error||!data?.signedUrl)throw appError('FILE_NOT_FOUND');res.statusCode=302;res.setHeader('Location',data.signedUrl);res.setHeader('Cache-Control','private, no-store, max-age=0');return res.end()}
async function prepareDownload(req,res){const user=await requireUser(req);await enforceRateLimit(db(),`video-download:${user.id}:${requestIp(req)}`,20,60);const id=cleanText(req.body?.videoId,100);await getOwnedVideo(user.id,id);const ticket=await createDownloadTicket({sub:user.id,imageId:id,kind:'video-download'},'2m');return json(res,200,{url:`/api/video?action=download&ticket=${encodeURIComponent(ticket)}`})}

async function submitVideo(req,res,locale){
  const user=await requireUser(req);await enforceRateLimit(db(),`video-submit:${user.id}:${requestIp(req)}`,6,60);const b=req.body||{};const conversationId=String(b.conversationId||''),prompt=cleanText(b.prompt,4000),taskId=cleanText(b.taskId,30).toLowerCase(),requestId=normalizeRequestId(b.requestId);
  if(!conversationId||!prompt)throw appError('INVALID_REQUEST');const s=db();await ensureConversationOwner(s,conversationId,user.id);
  const {data:profile,error:profileError}=await s.from('users').select('ai_tokens,has_purchased').eq('id',user.id).single();if(profileError||!profile)throw appError('DATABASE_ERROR',{},profileError);if(!profile.has_purchased)throw appError('MODEL_LOCKED');
  const models=(await getOpenRouterVideoModels()).sort((a,b)=>videoPricePerSecond(a)-videoPricePerSecond(b));if(!models.length)throw appError('MODEL_UNAVAILABLE');
  const configured=String((await getToolModelSettings()).video||'');const requested=cleanText(b.modelId,120);let model;
  if(taskId==='video')model=models.find(x=>x.id===configured)||models[0];else model=models.find(x=>x.id===requested)||models.find(x=>x.id===configured)||models[0];
  const sp=model.supported_parameters||{};const duration=chooseEnum(sp.duration,b.duration,['5','4','6','8'])||String(Math.max(1,Math.min(15,Number(b.duration)||5)));const resolution=chooseEnum(sp.resolution,b.resolution,['720p','1080p']);const aspectRatio=chooseEnum(sp.aspect_ratio,b.aspectRatio,['16:9','1:1']);
  const estimate=videoEstimate(model,duration,resolution,aspectRatio),reserved=reservationTokens(estimate.chargedTokens,'video'),available=Math.max(0,Number(profile.ai_tokens||0));if(available<reserved)throw appError('INSUFFICIENT_TOKENS_FOR_REQUEST',{availableTokens:available,requiredTokens:reserved,shortfall:reserved-available});
  if(!String(process.env.OPENROUTER_API_KEY||'').trim())throw appError('MISSING_CONFIGURATION',{missing:['OPENROUTER_API_KEY']});
  await reserveAiTokens(s,user.id,requestId,'video',reserved);let reservationActive=true,savedUser=null,savedAssistant=null,savedMedia=null;
  try{
    const body={model:model.id,prompt,generate_audio:false};if(duration)body.duration=Number.isFinite(Number(duration))?Number(duration):duration;if(resolution)body.resolution=resolution;if(aspectRatio)body.aspect_ratio=aspectRatio;
    const response=await fetchWithTimeout('https://openrouter.ai/api/v1/videos',{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${String(process.env.OPENROUTER_API_KEY).trim()}`,'HTTP-Referer':String(process.env.APP_URL||'https://aiway.app'),'X-Title':'AiWay'},body:JSON.stringify(body)},30000);
    const payload=await response.json().catch(()=>({}));if(!response.ok)throw appError('MODEL_UNAVAILABLE',{providerStatus:response.status},new Error(payload?.error?.message||`OpenRouter ${response.status}`));
    const jobId=String(payload?.id||'');const pollingUrl=validOpenRouterPollUrl(payload?.polling_url);if(!jobId||!pollingUrl)throw appError('EMPTY_RESPONSE');
    let q=await s.from('messages').insert({conversation_id:conversationId,user_id:user.id,role:'user',content:prompt,token_usage:{video_request:true,taskId:taskId||'video',duration,resolution,aspectRatio}}).select('id').single();if(q.error||!q.data)throw appError('DATABASE_ERROR',{},q.error);savedUser=q.data;
    q=await s.from('messages').insert({conversation_id:conversationId,user_id:user.id,role:'assistant',content:localize(locale,'جارٍ إنشاء الفيديو…','Generating the video…'),model_id:model.id,token_usage:{type:'video',taskId:taskId||'video',status:'processing',jobId,requestId,reservedTokens:reserved,providerUsdEstimate:estimate.providerUsd,duration,resolution,aspectRatio}}).select('id').single();if(q.error||!q.data)throw appError('DATABASE_ERROR',{},q.error);savedAssistant=q.data;
    q=await s.from('generated_images').insert({message_id:savedAssistant.id,conversation_id:conversationId,user_id:user.id,model_id:model.id,prompt,media_type:'video/mp4',source_url:null,thumbnail_data:null,storage_status:'processing',width:null,height:null,token_usage:{mediaKind:'video',jobId,pollingUrl,requestId,reservedTokens:reserved,providerUsdEstimate:estimate.providerUsd,chargedTokensEstimate:estimate.chargedTokens,duration,resolution,aspectRatio,expiresDays:3}}).select('*').single();if(q.error||!q.data)throw appError('DATABASE_ERROR',{},q.error);savedMedia=q.data;
    await s.from('conversations').update({updated_at:new Date().toISOString()}).eq('id',conversationId).eq('user_id',user.id);
    reservationActive=false;return json(res,202,{status:'processing',video:{...savedMedia},modelId:model.id,routedModelId:model.id,selectedModelName:model.name||model.id,estimate:{...estimate,reservedTokens:reserved},pollAfterMs:5000});
  }catch(error){if(savedMedia?.id)await s.from('generated_images').delete().eq('id',savedMedia.id).eq('user_id',user.id);if(savedAssistant?.id)await s.from('messages').delete().eq('id',savedAssistant.id).eq('user_id',user.id);if(savedUser?.id)await s.from('messages').delete().eq('id',savedUser.id).eq('user_id',user.id);if(reservationActive)await releaseAiTokens(s,user.id,requestId,{code:String(error?.code||'VIDEO_SUBMIT_FAILED')});throw error}
}

async function pollVideo(req,res,locale){
  const user=await requireUser(req),id=cleanText(req.body?.videoId,100),s=db();await enforceRateLimit(s,`video-poll:${user.id}:${requestIp(req)}`,30,60);let row=await getOwnedVideo(user.id,id);if(row.storage_status==='ready')return json(res,200,{status:'completed',video:{...row,display_url:await makeViewUrl(user.id,row.id)}});if(row.storage_status==='failed')return json(res,200,{status:'failed',error:localize(locale,'فشل إنشاء الفيديو، ولم يتم خصم الرصيد.','Video generation failed and your balance was not charged.')});
  const meta=row.token_usage||{},pollingUrl=validOpenRouterPollUrl(meta.pollingUrl);if(!pollingUrl)throw appError('INVALID_REQUEST');
  const response=await fetchWithTimeout(pollingUrl,{headers:{Authorization:`Bearer ${String(process.env.OPENROUTER_API_KEY||'').trim()}`,Accept:'application/json'}},15000);const status=await response.json().catch(()=>({}));if(!response.ok)throw appError('MODEL_UNAVAILABLE',{providerStatus:response.status});const state=String(status?.status||'processing').toLowerCase();
  if(!['completed','failed','cancelled','canceled'].includes(state))return json(res,200,{status:'processing',progress:status?.progress??null,pollAfterMs:5000});
  const requestId=String(meta.requestId||'');
  if(state!=='completed'){
    if(requestId)await releaseAiTokens(s,user.id,requestId,{code:'VIDEO_GENERATION_FAILED',jobId:meta.jobId||null});await s.from('generated_images').update({storage_status:'failed',fallback_reason:cleanText(status?.error?.message||status?.error||'provider_failed',300)}).eq('id',row.id).eq('user_id',user.id);await s.from('messages').update({content:localize(locale,'تعذر إنشاء الفيديو. لم يتم خصم الرصيد.','Video generation failed. Your balance was not charged.'),token_usage:{...(row.token_usage||{}),type:'video',status:'failed'}}).eq('id',row.message_id).eq('user_id',user.id);return json(res,200,{status:'failed',error:localize(locale,'تعذر إنشاء الفيديو. لم يتم خصم الرصيد.','Video generation failed. Your balance was not charged.')});
  }
  const jobId=cleanText(meta.jobId,180);if(!jobId)throw appError('EMPTY_RESPONSE');const contentUrl=`https://openrouter.ai/api/v1/videos/${encodeURIComponent(jobId)}/content?index=0`;const mediaResponse=await fetchWithTimeout(contentUrl,{headers:{Accept:'video/*',Authorization:`Bearer ${String(process.env.OPENROUTER_API_KEY||'').trim()}`}},120000);if(!mediaResponse.ok)throw appError('EMPTY_RESPONSE');const declared=String(mediaResponse.headers.get('content-type')||'').split(';')[0].toLowerCase();const length=Number(mediaResponse.headers.get('content-length')||0);if(length&&length>MAX_VIDEO_BYTES)throw appError('PAYLOAD_TOO_LARGE');const file=Buffer.from(await mediaResponse.arrayBuffer());if(!file.length||file.length>MAX_VIDEO_BYTES)throw appError('PAYLOAD_TOO_LARGE');const mediaType=detectVideoType(file,declared);if(!mediaType)throw appError('EMPTY_RESPONSE');
  const storagePath=`${user.id}/${row.id}.${extensionFor(mediaType)}`;const {error:uploadError}=await s.storage.from(VIDEO_BUCKET).upload(storagePath,file,{contentType:mediaType,cacheControl:'31536000',upsert:false});if(uploadError&&!/already exists|duplicate/i.test(String(uploadError.message||'')))throw appError('DATABASE_ERROR',{},uploadError);
  const actualUsd=Math.max(0,Number(status?.usage?.cost??status?.cost??meta.providerUsdEstimate??0));const actualTokens=Math.max(1,Math.ceil(actualUsd/TOKEN_USD));const reserved=Math.max(1,Number(meta.reservedTokens||actualTokens));const chargedTokens=Math.min(actualTokens,reserved);const remaining=await finalizeAiTokens(s,user.id,requestId,chargedTokens,{videoId:row.id,modelId:row.model_id,jobId:meta.jobId||null});
  const tokenUsage={...meta,status:'completed',providerUsd:actualUsd,chargedTokens,duration:meta.duration||null,resolution:meta.resolution||null,aspectRatio:meta.aspectRatio||null};const {data:updated,error:updateError}=await s.from('generated_images').update({media_type:mediaType,storage_path:storagePath,storage_status:'ready',file_size:file.length,stored_at:new Date().toISOString(),thumbnail_data:null,source_url:null,token_usage:tokenUsage,fallback_reason:null}).eq('id',row.id).eq('user_id',user.id).select('*').single();if(updateError||!updated)throw appError('DATABASE_ERROR',{},updateError);row=updated;
  await s.from('messages').update({content:localize(locale,'تم إنشاء الفيديو المطلوب.','The requested video has been generated.'),token_usage:{type:'video',taskId:'video',status:'completed',chargedTokens,providerUsd:actualUsd,duration:meta.duration||null,resolution:meta.resolution||null,aspectRatio:meta.aspectRatio||null}}).eq('id',row.message_id).eq('user_id',user.id);
  return json(res,200,{status:'completed',video:{...row,display_url:await makeViewUrl(user.id,row.id)},chargedTokens,providerUsd:actualUsd,remainingTokens:remaining,lowBalance:isLowBalance(remaining,chargedTokens)});
}

export default async function handler(req,res){if(!allowMethods(req,res,['GET','POST']))return;const locale=requestLocale(req);try{const action=String(req.body?.action||req.query?.action||'generate');if(action==='view'&&req.method==='GET')return await serveVideo(req,res,true);if(action==='download'&&req.method==='GET')return await serveVideo(req,res,false);if(req.method!=='POST')throw appError('INVALID_REQUEST');enforceJsonBodySize(req,1_000_000);if(action==='prepare-download')return await prepareDownload(req,res);if(action==='poll')return await pollVideo(req,res,locale);return await submitVideo(req,res,locale)}catch(error){console.error('[VIDEO_API]',error?.code||error?.message||error);if(error?.code==='FILE_NOT_FOUND'){const details=errorDetails(error,locale);return json(res,404,{error:details.message,code:'FILE_NOT_FOUND'})}return handleError(error,res,localize(locale,'تعذر تنفيذ طلب الفيديو. حاول مرة أخرى.','Could not complete the video request. Try again.'),locale)}}
